name: speech-map-cpu
channels:
  - conda-forge
dependencies:
  - python>=3.12
  - faiss-cpu>=1.9.0
  - numpy==1.26.4
  - polars>=1.30.0
  - pytorch-cpu>=2.7.0
  - tqdm>=4.67.1
  - pip:
    - speech-map>=0.1.0
